stages:
  - compile

.x-test: &with-test
  image: node
  script:
    - make test

.x-when-mr: &when-merge-request
  only:
    - merge_requests

.x-when-stable: &when-in-stable
  only:
    - main

.x-when-stable-or-mr: &when-stable-or-mr
  only:
    - main
    - merge_requests


lint:
  <<: *when-stable-or-mr
  interruptible: true
  stage: compile
  image: node
  tags:
    - docker
  script:
    - |
      make format
      touched=$(git status --porcelain | wc -l) || touched=0
      if [ $touched -gt 0 ]; then
          git status
          exit 1
      fi

test:
  <<: *with-test
  <<: *when-stable-or-mr
  interruptible: true
  stage: compile
  tags:
    - docker
